MOSMODEL_STRATEGIES := moselect
MOSMODEL_TRAIN_LAYOUT_GENERATORS_moselect := moselect
MOSELECT_NUM_OF_REPEATS := 2
MOSELECT_NUM_LAYOUTS := 17
DEFAULT_NUM_OF_REPEATS := 2
STOP_POLICY := TO_COMPLETION
FIXED_DURATION_SEC := 20